### ISSUE TITLE
Mac OSX app is damaged?

### ISSUE THREAD

**Issue by blechdom** [kasperkamperman/OSCDataMonitor#1]
Received this message after trying to open the mac osx version of the app: “OSC_Data_Monitor.app” is damaged and can’t be opened. You should move it to the Trash.

I'm running Mac OSX Sierra 10.12.5

**Comment by kasperkamperman** [comment]
I've mentioned this in the readme:

Take in account that the Mac Application is not signed. The Mac Gatekeeper might say that it's not signed and refuse to run. If the application will not run, try right-clicking the app and selecting Open from the pop-up menu. Or you can visit "System Preferences > Security & Privacy and select Allow apps downloaded from: anywhere. (Of course use at your own risk.)

**Comment by kasperkamperman** [comment]
By the way. If you don't want to take that risk. Just download Processing and run the code from there.

**Comment by blechdom** [comment]
thanks. I will run from processing. looking forward. Seems like the it's not just a signing issue, since I often am able to bypass security gatekeeper for other unsigned apps, but not this one.

**Comment by kasperkamperman** [comment]
I was considering a signed export, but that involved too much work.

**Comment by blechdom** [comment]
It's working great with processing, after I installed the oscP5 and controlP5 libraries. reminds me of OSC Shark. thanks!
